server:
  port: 8080

spring:
  application:
    name: CrawlLangAI
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      chat:
        options:
          model: ${CHAT_MODEL:qwen3-4b}
          max-tokens: ${MAX_TOKEN:8192}
      embedding:
        options:
          model: ${EMBEDDING_MODEL:text-embedding-v3}
      base-url: ${DASHSCOPE_BASE_URL:192.168.0.104}
    memory:
      redis:
        host: ${HOST}
        port: 6379
        password: ${PASSWORD}
        timeout: 2000
  datasource:
    url: ${DB_URL:jdbc:mysql://127.0.0.1:3306/crawllangai?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
  neo4j:
    authentication:
      password: ${NEO4J_PASSWORD}
      username: neo4j
    uri: neo4j+s://86a3bac1.databases.neo4j.io